PROJECT_NAME=image-block-x
EXCLUDE := .git .gitignore Makefile **/*.md
SOURCE=ImageBlockX
ASSETS=assets


make:
	cd ${SOURCE}; zip -r ${PROJECT_NAME}.zip * -x ${EXCLUDE}; mv ${PROJECT_NAME}.zip ..; cd -

.PHONY: clean help
clean:  ## Remove autogenerated files
	rm -fv ${PROJECT_NAME}.zip

help:  ## Print this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| sort \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
